---
gameTitle: Jessica's memories
saveFileName: Jessica's memories
dialogPanel:
  overlayMode: true
  rightOffset: 100
  bottomOffset: 50
  width: 495
  height: 680
  textSpeed: 20
  animateText: true
  timeBetweenLines: 100
layout:
  backgrounds:
    width: 1280
    height: 720
  dialogBottomPadding: 70
  mobileDialogHeightPercentage: 60
  verticalLayoutThreshold: 600
  portraits:
    width: 225
    height: 225
notifications:
  timeOnScreen: 1.5
  alsoPrintInDialogue: true
hudStats:
  money:
    icon: img/ui/money.webp
    name: Money
    hideName: true
    startingValue: 10
    minValue: 0
saves:
  mode: manual
  slots: 10
